### ISSUE TITLE
Discrepency in maximum number of client connections in latest release candidate

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#3223]
Date: 2013-01-16 09:54:37 +0100
From: Ashish Kumar Singh &lt;<ashishk>&gt;
To:   GDK devs &lt;<bugs-common>&gt;
Version: 11.15.1 (Feb2013)
CC:   ashishk

Last updated: 2013-01-16 11:03:47 +0100

## Comment 18342
Date: 2013-01-16 09:54:37 +0100
From: Ashish Kumar Singh &lt;<ashishk>&gt;

User-Agent:       Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17
 Build Identifier: 
 
 I tried pointing to October 2012 SP3 release candidate from my working application on top of October 2012 SP1 build.
 
 
 With nclient set to 64 it started showing me following error:
 
 maximum concurrent client limit reached (193), please try again later
 
 With nclient =200 it started showing me below error
 
 maximum concurrent client limit reached (601), please try again later
 
 	at com.altair.pbsworks.parser.datamodel.ParsedRescourceConatinerEventResourceOccupancyDetails.convertValues(ParsedRescourceConatinerEventResourceOccupancyDetails.java:384)
 	at com.altair.pbsworks.parser.app.RescourceConatinerEventResourceOccupancyDetailsPopulatorThread.run(RescourceConatinerEventResourceOccupancyDetailsPopulatorThread.java:44)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
 	at java.lang.Thread.run(Thread.java:662)
 Caused by: nl.cwi.monetdb.mcl.MCLException: maximum concurrent client limit reached (601), please try again later
 	at nl.cwi.monetdb.mcl.net.MapiSocket.connect(MapiSocket.java:308)
 	at nl.cwi.monetdb.mcl.net.MapiSocket.connect(MapiSocket.java:395)
 	at nl.cwi.monetdb.mcl.net.MapiSocket.connect(MapiSocket.java:248)
 	at nl.cwi.monetdb.jdbc.MonetConnection.<init>(MonetConnection.java:232)
 	... 612 more
 
 
 Need information on if something got changed in this particular area?
 
 
 
 Regards,
 Ashish
 
 Reproducible: Always

## Comment 18343
Date: 2013-01-16 11:03:47 +0100
From: Ashish Kumar Singh &lt;<ashishk>&gt;

Not an issue with monetdb, please ignore it.

**Comment by raaahuuulll** [comment]
Hi,
Can somebody  please tell me how do I increase the maximum concurrent clients limit.
