### ISSUE TITLE
AddressSanitizer:DEADLYSIGNAL in Oct2020/gdk/gdk_tracer.c:494

### ISSUE THREAD

**Issue by yzchang** [MonetDB/MonetDB#7042]
**Describe the bug**
When sanitiser is enabled, starting `mserver5` with a `dbpath` beginning with a `~` triggers an error:
```
$ mserver5 --dbpath=~/test
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1927925==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fda39aa96a7 bp 0x7ffd9a3aa840 sp 0x7ffd9a3a9fb8 T0)
==1927925==The signal is caused by a READ memory access.
==1927925==Hint: address points to the zero page.
    #0 0x7fda39aa96a6  (/lib/x86_64-linux-gnu/libc.so.6+0x18b6a6)
    #1 0x7fda3b9e08fb  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x678fb)
    #2 0x7fda3ad734a0 in GDKtracer_log /home/vagrant/shared/monetdb/mdb-src/Oct2020/gdk/gdk_tracer.c:494
    #3 0x7fda3a8e0098 in BBPaddfarm /home/vagrant/shared/monetdb/mdb-src/Oct2020/gdk/gdk_bbp.c:1146
    #4 0x556600cc7b12 in main /home/vagrant/shared/monetdb/mdb-src/Oct2020/tools/mserver/mserver5.c:554
    #5 0x7fda399450b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #6 0x556600cc4bcd in _start (/home/vagrant/shared/monetdb/mdb-nst/Oct2020/bin/mserver5+0x6bcd)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x18b6a6)
==1927925==ABORTING
```
Without the sanitizer, I get
```
$ mserver5 --dbpath=~/test
#unknown thread: BBPaddfarm: !ERROR: /home/vagrant/shared/monetdb/mdb-src/~/test: cannot create directory: No such file or directory
!ERROR: cannot add farm
```
**Expected behavior**
Start the database or a proper error.

**Screenshots**

**Software versions**
 - MonetDB version number [Oct2020 (hg id 0dbe3839e358)]
 - OS and version: [e.g. Ubuntu 20.04]
 - Mercurial source

**Comment by sjoerdmullender** [comment]
I think I know why this is.  I'll come up with a fix.
