### ISSUE TITLE
COLnew_intern: Assertion `cap <= BUN_MAX' failed.

### ISSUE THREAD

**Issue by skinkie** [MonetDB/MonetDB#7269]
**Describe the bug**
When operating a daily query, since this moring the database crashes on it, reporting the following merovingian error.

2022-03-15 10:01:32 MSG merovingian[16291]: target connection is on local UNIX domain socket, passing on filedescriptor instead of proxying
2022-03-15 10:01:37 ERR htm[551514]: mserver5: /home/skinkie/MonetDB/gdk/gdk_bat.c:247: COLnew_intern: Assertion `cap <= BUN_MAX' failed.
2022-03-15 10:01:41 MSG merovingian[16291]: database 'htm' (-1) has crashed with signal SIGABRT (dumped core)

**To Reproduce**
On my local installation I can reproduce this error by executing a query, that did not have any issues in the past years. But my expectation is that this also implies to have a database of similar size, over thousand tables.

**Expected behavior**
The query executes.

**Software versions**
 - MonetDB 5 server 11.42.0 (hg id: d8bce54d40) (64-bit, 128-bit integers)
 - OS and version: 5.16.10-arch1-1

**Additional context**
Access to the offending query and database are obviously available on request. I am sure that a clean database resolves this issue, but I may have hit a way interesting enough to investigate.

**Comment by sjoerdmullender** [comment]
Do you have a stack trace?
What is the actual value of `cap`, and where did that come from?

**Comment by skinkie** [comment]
> Do you have a stack trace?

Is there a way to get that from merovingian? Or start the database in gdb if started before from monetdbd?

```
[skinkie@database ~]$ gdb --args /opt/monetdb-2021/bin/mserver5 --dbpath=/home/monetdb-2021/htm --set merovingian_uri mapi:monetdb://database:50000/htm --set mapi_listenaddr none --set mapi_usock /home/monetdb-2021/htm/.mapi.sock --set monet_vault_key /home/monetdb-2021/htm/.vaultkey --set gdk_nr_threads 12 --set max_clients 64 --set sql_optimizer default_pipe
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/monetdb-2021/bin/mserver5...
(No debugging symbols found in /opt/monetdb-2021/bin/mserver5)
(gdb) r
Starting program: /opt/monetdb-2021/bin/mserver5 --dbpath=/home/monetdb-2021/htm --set merovingian_uri mapi:monetdb://database:50000/htm --set mapi_listenaddr none --set mapi_usock /home/monetdb-2021/htm/.mapi.sock --set monet_vault_key /home/monetdb-2021/htm/.vaultkey --set gdk_nr_threads 12 --set max_clients 64 --set sql_optimizer default_pipe
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
ERROR: wrong format merovingian_uri
ERROR: wrong format mapi_listenaddr
ERROR: wrong format mapi_usock
ERROR: wrong format monet_vault_key
ERROR: wrong format gdk_nr_threads
ERROR: wrong format max_clients
ERROR: wrong format sql_optimizer
Usage: /opt/monetdb-2021/bin/mserver5 [options]
    --dbpath=<directory>      Specify database location
    --dbextra=<directory>     Directory for transient BATs
    --dbtrace=<file>          File for produced traces
    --in-memory               Run database in-memory only
    --config=<config_file>    Use config_file to read options from
    --single-user             Allow only one user at a time
    --readonly                Safeguard database
    --set <option>=<value>    Set configuration option
    --help                    Print this list of options
    --version                 Print version and compile time info
The debug, testing & trace options:
     --algorithms
     --forcemito
     --heaps
     --io
     --memory
     --modules
     --performance
     --properties
     --threads
     --transactions
     --debug=<bitmask>
[Inferior 1 (process 555053) exited with code 0377]
quit) 
```

**Comment by skinkie** [comment]
```
(gdb) bt
#0  0x00007ffff6bc534c in __pthread_kill_implementation () from /usr/lib/libc.so.6
#1  0x00007ffff6b784b8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff6b62534 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff6b6245c in __assert_fail_base.cold () from /usr/lib/libc.so.6
#4  0x00007ffff6b71116 in __assert_fail () from /usr/lib/libc.so.6
#5  0x00007ffff7604ffb in COLnew_intern (hseq=0, tt=7, cap=13672292666396492835, role=TRANSIENT, width=0)
    at /home/skinkie/MonetDB/gdk/gdk_bat.c:247
#6  0x00007ffff7605867 in COLnew (hseq=0, tt=7, cap=13672292666396492835, role=TRANSIENT) at /home/skinkie/MonetDB/gdk/gdk_bat.c:311
#7  0x00007ffff7641a88 in BATgroup_internal (groups=0x7fffed6a9538, extents=0x7fffed6a9540, histo=0x0, b=0x7fffb0001270, s=0x0, 
    g=0x7fffb0002b20, e=0x0, h=0x0, subsorted=false) at /home/skinkie/MonetDB/gdk/gdk_group.c:816
#8  0x00007ffff767a93c in BATgroup (groups=0x7fffed6a9538, extents=0x7fffed6a9540, histo=0x0, b=0x7fffb0001270, s=0x0, g=0x7fffb0002b20, 
    e=0x0, h=0x0) at /home/skinkie/MonetDB/gdk/gdk_group.c:1310
#9  0x00007ffff7e1116a in GRPsubgroup5 (ngid=0x7fffd816f480, next=0x7fffd816f4a0, nhis=0x0, bid=0x7fffd816efa0, sid=0x0, 
    gid=0x7fffd816f1a0, eid=0x0, hid=0x0) at /home/skinkie/MonetDB/monetdb5/modules/kernel/group.c:42
#10 0x00007ffff7e11440 in GRPsubgroup6 (ngid=0x7fffd816f480, next=0x7fffd816f4a0, bid=0x7fffd816efa0, gid=0x7fffd816f1a0)
    at /home/skinkie/MonetDB/monetdb5/modules/kernel/group.c:87
#11 0x00007ffff7cc5739 in malCommandCall (stk=0x7fffd8160010, pci=0x7fffd8144d90)
    at /home/skinkie/MonetDB/monetdb5/mal/mal_interpreter.c:61
#12 0x00007ffff7cc8aa2 in runMALsequence (cntxt=0x555556d52700, mb=0x7fffd8006a20, startpc=400, stoppc=401, stk=0x7fffd8160010, env=0x0, 
    pcicaller=0x0) at /home/skinkie/MonetDB/monetdb5/mal/mal_interpreter.c:678
#13 0x00007ffff7ccce36 in DFLOWworker (T=0x7ffff7f881e0 <workers+384>) at /home/skinkie/MonetDB/monetdb5/mal/mal_dataflow.c:400
#14 0x00007ffff759f9ca in THRstarter (a=0x7fffd80de460) at /home/skinkie/MonetDB/gdk/gdk_utils.c:1608
#15 0x00007ffff76198b2 in thread_starter (arg=0x555559e54b50) at /home/skinkie/MonetDB/gdk/gdk_system.c:820
#16 0x00007ffff6bc35c2 in start_thread () from /usr/lib/libc.so.6
#17 0x00007ffff6c48584 in clone () from /usr/lib/libc.so.6
```

**Comment by skinkie** [comment]
Executed query.

```sql
copy (select operatingday as datum, split_part(trip_id, ':', 2) as lijn, split_part(trip_id, ':', 3) as ritnr, geplande_vertrek, geplande_aankomst, time32diff(geplande_vertrek, geplande_aankomst) as dru_tijd, eerste_halte, laatste_halte, aantal_haltes, '1' as has_kv1, cast((coalesce(arrivals, coalesce(departures, 0)) > 0) as tinyint) as has_kv6, coalesce(arrivals, 0) as count_arrivals, vehiclenumber, werkelijke_vertrek, werkelijke_aankomst, epoch(werkelijke_aankomst) - epoch(werkelijke_vertrek) as werkelijke_dru_tijd, coalesce(departures, 0) as count_departures, (kv17b.messagetype is not null) as has_kv17, reasontype, reasoncontent

from (select a.trip_hash, a.operatingday, a.trip_id, a.targetdeparturetime as geplande_vertrek, b.targetarrivaltime as geplande_aankomst, coalesce(au.name, 'ONBEKEND') as eerste_halte, coalesce(bu.name, 'ONBEKEND') as laatste_halte, aantal_haltes, 1 as count from (select trip_hash, count(*) as aantal_haltes, min(pointorder) as min_pointorder, max(pointorder) as max_pointorder from tt_20220314 group by trip_hash) as trips join tt_20220314 as a on (min_pointorder = a.pointorder and trips.trip_hash = a.trip_hash) join tt_20220314 as b on (max_pointorder = b.pointorder and trips.trip_hash = b.trip_hash) left join htmhalte as au on (au.userstopcode = a.userstopcode) left join htmhalte as bu on (bu.userstopcode = b.userstopcode)) as z

left join (select min(vehicle) as werkelijke_vertrek, vehiclenumber, trip_hash from kv6_20220314 where messagetype = 'DEPARTURE' group by trip_hash, vehiclenumber) as u using (trip_hash) 
left join (select max(vehicle) as werkelijke_aankomst, vehiclenumber, trip_hash from kv6_20220314 where messagetype = 'ARRIVAL' OR messagetype = 'DEPARTURE' group by trip_hash, vehiclenumber) as y using (trip_hash, vehiclenumber) 
left join (select count(*) as arrivals, trip_hash, vehiclenumber from (select distinct trip_hash, userstopcode, vehiclenumber from kv6_20220314 where messagetype = 'ARRIVAL') as d_a group by trip_hash, vehiclenumber) as v using (trip_hash, vehiclenumber) 
left join (select count(*) as departures, trip_hash, vehiclenumber from (select distinct trip_hash, userstopcode, vehiclenumber from kv6_20220314 where messagetype = 'DEPARTURE') as d_d group by trip_hash, vehiclenumber) as w using (trip_hash, vehiclenumber)

left join (select messagetype, reasontype, reasoncontent, kv17_20220314.trip_hash from kv17_20220314 join (select max(message) as last, trip_hash from kv17_20220314 group by trip_hash) as kv17a on (kv17_20220314.trip_hash = kv17a.trip_hash and last = kv17_20220314.message) where messagetype = 'CANCEL') as kv17b using (trip_hash)) into '/tmp/export/htm/export-20220314.csv' DELIMITERS ',' NULL AS '';
```

**Comment by sjoerdmullender** [comment]
I can't figure out which version you're using exactly, but I do see it's old.  What about upgrading to something more up-to-date first?   You can stay on the same branch (Jul2021) but then use the tip of the branch.

**Comment by PedroTadim** [comment]
I got this assertion by fuzzing on default last week. Let me ask Niels if he allows me to try it again :)

**Comment by skinkie** [comment]
> I can't figure out which version you're using exactly, but I do see it's old. What about upgrading to something more up-to-date first? You can stay on the same branch (Jul2021) but then use the tip of the branch.

After checking out the last SP4 commit (I _still_ unable to checkout a remote git branch it just doesn't work when doing origin/branches/July2021)  the query completed without an incident.

**Comment by skinkie** [comment]
I missed the reply of @PedroTadim before I closed it, if you think this is resolved. The database (and original server debug-binaries) are still available.

**Comment by PedroTadim** [comment]
I found the culprit on my side, an overflow on the output size. Let's close the issue for now.
