### ISSUE TITLE
MonetDB Dec2023-SP2 crashes with the `GET_MERGE_TABLE_PARTITION_EXPRESSIONS` function

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7512]
**Describe the bug**
MonetDB Dec2023-SP2 crashes with the `GET_MERGE_TABLE_PARTITION_EXPRESSIONS` function.

**To Reproduce**
```sql
SELECT GET_MERGE_TABLE_PARTITION_EXPRESSIONS('');
SELECT GET_MERGE_TABLE_PARTITION_EXPRESSIONS(0);
```

**Backtrace of the Crash**
```
#0  0x00007f55d352f0b5 in bind_col () from target:/usr/local/lib/libmonetdbsql.so.14
#1  0x00007f55d341e824 in mvc_bind_wrap () from target:/usr/local/lib/libmonetdbsql.so.14
#2  0x00007f55d53511b8 in runMALsequence () from target:/usr/local/lib/libmonetdb5.so.35
#3  0x00007f55d5353c0a in DFLOWworker () from target:/usr/local/lib/libmonetdb5.so.35
#4  0x00007f55d4714eed in thread_starter () from target:/usr/local/lib/libbat.so.28
#5  0x00007f55d4064609 in start_thread () from target:/lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f55d3f89353 in clone () from target:/lib/x86_64-linux-gnu/libc.so.6
```

**Software versions**
 - MonetDB version number: v11.49.7 (Dec2023-SP2)
 - OS and version: Ubuntu 20.04
 - From docker image monetdb/monetdb:Dec2023-SP2 (or monetdb/dev-builds:default)

**Comment by njnes** [comment]
fixed by adding locks around instantiation of global tmps
