### ISSUE TITLE
MonetDB Dec2023-SP2 crashes with the `GETHOST` function

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7513]
**Describe the bug**
MonetDB Dec2023-SP2 crashes with the `GETHOST` function.

**To Reproduce**
```sql
SELECT GETHOST('https://me:pw@www.monetdb.org/Doc');
SELECT GETHOST('https://me:pw@www.monetdb.org/Doc');
SELECT GETHOST('https://me:pw@www.monetdb.org/Doc');
```

**Backtrace of the Crash**
```
#0  0x00007f6586d289e5 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f65874ae017 in GDKfree () from target:/usr/local/lib/libbat.so.28
#2  0x00007f658753eb3b in VALclear () from target:/usr/local/lib/libbat.so.28
#3  0x00007f6588176a2d in resetMalBlk () from target:/usr/local/lib/libmonetdb5.so.35
#4  0x00007f6586255b72 in SQLrun () from target:/usr/local/lib/libmonetdbsql.so.14
#5  0x00007f6586256d7c in SQLengineIntern () from target:/usr/local/lib/libmonetdbsql.so.14
#6  0x00007f658625531a in SQLengine_ () from target:/usr/local/lib/libmonetdbsql.so.14
#7  0x00007f658625591b in SQLengine () from target:/usr/local/lib/libmonetdbsql.so.14
#8  0x00007f6588190826 in runScenario () from target:/usr/local/lib/libmonetdb5.so.35
#9  0x00007f6588191140 in MSscheduleClient () from target:/usr/local/lib/libmonetdb5.so.35
#10 0x00007f6588240922 in doChallenge () from target:/usr/local/lib/libmonetdb5.so.35
#11 0x00007f658753ceed in thread_starter () from target:/usr/local/lib/libbat.so.28
#12 0x00007f6586e8c609 in start_thread () from target:/lib/x86_64-linux-gnu/libpthread.so.0
#13 0x00007f6586db1353 in clone () from target:/lib/x86_64-linux-gnu/libc.so.6
```

**Software versions**
 - MonetDB version number: v11.49.7 (Dec2023-SP2)
 - OS and version: Ubuntu 20.04
 - From docker image monetdb/monetdb:Dec2023-SP2 (or monetdb/dev-builds:default)

**Comment by njnes** [comment]
fixed authority parsing part (ie reset port after finding user:pw).
