### ISSUE TITLE
Assertion failure when using `STARTSWITH`

### ISSUE THREAD

**Issue by suyZhong** [MonetDB/MonetDB#7540]
**Describe the bug**
The following test case crashed the monetdb server.

**To Reproduce**

```sql
DROP TABLE IF EXISTS t0 CASCADE;
DROP TABLE IF EXISTS t1 CASCADE;

CREATE TABLE  t1 (c0 BOOLEAN , c1 INT);
CREATE TABLE  t0 (c0 BOOLEAN , c1 INT);
INSERT INTO t1(c0) VALUES (true);
INSERT INTO t1(c0) VALUES (false);
INSERT INTO t0(c1, c0) VALUES (false, true);
INSERT INTO t0(c0) VALUES (false);

SELECT * FROM t1, t0 WHERE STARTSWITH(t1.c1, '', t0.c1); -- unexpected end of file
```

**Expected behavior**
No crash.

**Screenshots**

backtrace (using gdb):

```#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139835803805248) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139835803805248) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139835803805248, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f2e188ff476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f2e188e57f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f2e188e571b in __assert_fail_base (fmt=0x7f2e18a9a130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x7f2e1a2d14df "BATcount(c) == 1", file=0x7f2e1a2d0ba8 "/app/MonetDB/monetdb5/modules/atoms/str.c", 
    line=2878, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007f2e188f6e96 in __GI___assert_fail (assertion=0x7f2e1a2d14df "BATcount(c) == 1", 
    file=0x7f2e1a2d0ba8 "/app/MonetDB/monetdb5/modules/atoms/str.c", line=2878, 
    function=0x7f2e1a2d2eb8 <__PRETTY_FUNCTION__.0> "ignorecase") at ./assert/assert.c:101
#7  0x00007f2e1a10d32f in ignorecase () from /usr/local/lib/libmonetdb5-11.52.0.so.35
#8  0x00007f2e1a10d635 in STRstartswithjoin () from /usr/local/lib/libmonetdb5-11.52.0.so.35
#9  0x00007f2e1a0c8249 in runMALsequence () from /usr/local/lib/libmonetdb5-11.52.0.so.35
#10 0x00007f2e1a0cc1a2 in DFLOWworker () from /usr/local/lib/libmonetdb5-11.52.0.so.35
#11 0x00007f2e193999d3 in thread_starter () from /usr/local/lib/libbat-11.52.0.so.28
#12 0x00007f2e18951ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#13 0x00007f2e189e2a04 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

**Software versions**
Build from source https://www.monetdb.org/documentation-Aug2024/dev-guide/installation-from-source/#summary:

```
> docker exec -it monetdb-test mserver5 --version
MonetDB 5 server 11.52.0 (hg id: 736987f) (64-bit, 128-bit integers)
This is an unreleased version
Copyright (c) 1993 - July 2008 CWI
Copyright (c) August 2008 - 2023 MonetDB B.V., all rights reserved
Visit https://www.monetdb.org/ for further information
Found 503.5GiB available memory, 128 available cpu cores
Libraries:
Compiled by: @2195e8c5ad70 (x86_64-pc-linux-gnu)
Compilation: /usr/bin/cc 
Linking    : /usr/bin/ld
```

**Issue labeling**
Bug

**Additional context**

**Comment by lrpereira** [comment]
Fixed in Aug2024.
Thanks for the report!
