### ISSUE TITLE
Crash when creating view with `GROUP BY`

### ISSUE THREAD

**Issue by suyZhong** [MonetDB/MonetDB#7545]
**Describe the bug**
The following test case crashed the monetdb server.

**To Reproduce**

```sql
DROP TABLE IF EXISTS t0 CASCADE;

CREATE TABLE t0 (c0 VARCHAR, c1 VARCHAR ) ;
CREATE UNIQUE INDEX i0 ON t0(c0 ); 
CREATE VIEW v0(c0) AS SELECT t0.c1 FROM t0 GROUP BY (CASE (NULL) WHEN t0.c1 THEN t0.c0 END ); -- unexpected end of file
```

**Expected behavior**
No crash.

**Screenshots**

backtrace (using gdb):

```
#0  0x00007ff6c8a0cdb8 in group_by_pk_project_uk_cond () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#1  0x00007ff6c8a0e89e in rel_column_ref () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#2  0x00007ff6c8a2463d in rel_value_exp2 () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#3  0x00007ff6c8a25016 in rel_value_exp () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#4  0x00007ff6c8a25148 in column_exp () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#5  0x00007ff6c8a25a2d in rel_column_exp () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#6  0x00007ff6c8a26cf3 in rel_select_exp () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#7  0x00007ff6c8a2782a in rel_query () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#8  0x00007ff6c8a2950e in rel_subquery () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#9  0x00007ff6c8a29708 in rel_selects () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#10 0x00007ff6c8a29827 in schema_selects () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#11 0x00007ff6c8a3e1e3 in rel_create_view () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#12 0x00007ff6c8a457cf in rel_schemas () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#13 0x00007ff6c8a05a89 in rel_semantic () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#14 0x00007ff6c8821e13 in sql_symbol2relation () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#15 0x00007ff6c884f922 in SQLparser_body () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#16 0x00007ff6c8850a16 in SQLparser () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#17 0x00007ff6c8850bb5 in SQLengine_ () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#18 0x00007ff6c8850c8b in SQLengine () from /usr/local/lib/libmonetdbsql-11.52.0.so.14
#19 0x00007ff6cadb4009 in runScenarioBody () from /usr/local/lib/libmonetdb5-11.52.0.so.35
#20 0x00007ff6cadb4117 in runScenario () from /usr/local/lib/libmonetdb5-11.52.0.so.35
#21 0x00007ff6cadb6159 in MSserveClient () from /usr/local/lib/libmonetdb5-11.52.0.so.35
#22 0x00007ff6cadb5964 in MSscheduleClient () from /usr/local/lib/libmonetdb5-11.52.0.so.35
#23 0x00007ff6caeb95ab in doChallenge () from /usr/local/lib/libmonetdb5-11.52.0.so.35
#24 0x00007ff6ca06216c in thread_starter () from /usr/local/lib/libbat-11.52.0.so.28
#25 0x00007ff6c95b1ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#26 0x00007ff6c9642a04 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

**Software versions**
Build from source https://www.monetdb.org/documentation-Aug2024/dev-guide/installation-from-source/#summary:

```
> docker exec -it monetdb-test mserver5 --version
MonetDB 5 server 11.52.0 (hg id: 53f9d56) (64-bit, 128-bit integers)
This is an unreleased version
Copyright (c) 1993 - July 2008 CWI
Copyright (c) August 2008 - 2023 MonetDB B.V., all rights reserved
Visit https://www.monetdb.org/ for further information
Found 503.5GiB available memory, 128 available cpu cores
Libraries:
Compiled by: @49c6d00b8d79 (x86_64-pc-linux-gnu)
Compilation: /usr/bin/cc 
Linking    : /usr/bin/ld
```

**Issue labeling**
Bug

**Additional context**

**Comment by lrpereira** [comment]
Thanks for the report.
Fixed in Aug2024 branch.
