### ISSUE TITLE
Assertion failure at `rel2bin_select` when using `STARTSWITH` 

### ISSUE THREAD

**Issue by suyZhong** [MonetDB/MonetDB#7574]
### Describe the bug

The following test case crashed the monetdb server. Not sure if it's related to https://github.com/MonetDB/MonetDB/issues/7556. The previous one works well on my tested verion.

### Reproduction steps

```sql
DROP TABLE IF EXISTS t1 CASCADE;
DROP VIEW IF EXISTS v0 CASCADE;

CREATE  TABLE  t1(c0 INTEGER, c1 VARCHAR);
CREATE VIEW v0(c0) AS SELECT 'a' FROM t1;

SELECT * FROM t1, v0 WHERE STARTSWITH(t1.c0, v0.c0, t1.c1); 

```

### Expected behavior

No crash

### MonetDB release

MonetDB v11.52.0 (hg id: 7fee05b)

### Executables source

Self compiled and installed

### Operating System

Ubuntu 22.04

### Additional context

Build from source https://www.monetdb.org/documentation-Aug2024/dev-guide/installation-from-source/#summary

Backtrace:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140626863236672) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140626863236672) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140626863236672, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fe64f85d476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fe64f8437f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fe64f84371b in __assert_fail_base (fmt=0x7fe64f9f8130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x7fe64ee59957 "sql->session->status == -10", 
    file=0x7fe64ee59310 "/app/MonetDB/sql/backends/monet5/rel_bin.c", line=4582, function=<optimized out>)
    at ./assert/assert.c:92
#6  0x00007fe64f854e96 in __GI___assert_fail (assertion=0x7fe64ee59957 "sql->session->status == -10", 
    file=0x7fe64ee59310 "/app/MonetDB/sql/backends/monet5/rel_bin.c", line=4582, 
    function=0x7fe64ee5a520 <__PRETTY_FUNCTION__.32> "rel2bin_select") at ./assert/assert.c:101
#7  0x00007fe64eb8d32c in rel2bin_select () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#8  0x00007fe64eb9ba2b in subrel_bin () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#9  0x00007fe64eb85f50 in rel2bin_join () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#10 0x00007fe64eb9b8b9 in subrel_bin () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#11 0x00007fe64eb8c309 in rel2bin_project () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#12 0x00007fe64eb9b9fd in subrel_bin () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#13 0x00007fe64eb9be57 in output_rel_bin () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#14 0x00007fe64ebd1f35 in sql_relation2stmt () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#15 0x00007fe64ebd216a in backend_dumpstmt_body () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#16 0x00007fe64ebd2551 in backend_dumpstmt () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#17 0x00007fe64eb64f1e in SQLparser_body () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#18 0x00007fe64eb65b02 in SQLparser () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#19 0x00007fe64eb65ca1 in SQLengine_ () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#20 0x00007fe64eb65d77 in SQLengine () from /usr/local/lib/libmonetdbsql-11.52.0.so.15
#21 0x00007fe6511a1b8d in runScenarioBody () from /usr/local/lib/libmonetdb5-11.52.0.so.36
#22 0x00007fe6511a1c9b in runScenario () from /usr/local/lib/libmonetdb5-11.52.0.so.36
#23 0x00007fe6511a3d94 in MSserveClient () from /usr/local/lib/libmonetdb5-11.52.0.so.36
#24 0x00007fe6511a359f in MSscheduleClient () from /usr/local/lib/libmonetdb5-11.52.0.so.36
#25 0x00007fe6512a770e in doChallenge () from /usr/local/lib/libmonetdb5-11.52.0.so.36
#26 0x00007fe65035c5e6 in thread_starter () from /usr/local/lib/libbat-11.52.0.so.29
#27 0x00007fe64f8afac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#28 0x00007fe64f940a04 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

**Comment by njnes** [comment]
we now delay the push down of filter functions.
