### ISSUE TITLE
monetdbe: cannot monetdbe.connect(':memory:'): wrong offset for field 'remote'

### ISSUE THREAD

**Issue by glycerine** [MonetDB/MonetDB#7608]
### Describe the bug

on macOS Sonoma 14
python v3.11.6
monetdbe version 0.11

Following the basic getting started for monetdbe under python results in an immediate error. See below.  I was following the instructions here https://www.monetdb.org/documentation-Aug2024/dev-guide/mbedded-python/

### Reproduction steps

installation:
~~~
jaten@Js-MacBook-Pro ~ $ mkdir monetdbe
jaten@Js-MacBook-Pro ~ $ python3 -m venv monetdbe
jaten@Js-MacBook-Pro ~ $ source monetdbe/bin/activate
(monetdbe) jaten@Js-MacBook-Pro ~ $ pip install monetdbe
Collecting monetdbe
  Downloading monetdbe-0.11.tar.gz (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 107.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi>=1.0.0 (from monetdbe)
  Obtaining dependency information for cffi>=1.0.0 from https://files.pythonhosted.org/package\
s/6b/f4/927e3a8899e52a27fa57a48607ff7dc91a9ebe97399b357b85a0c7892e00/cffi-1.17.1-cp311-cp311-m\
acosx_10_9_x86_64.whl.metadata
  Using cached cffi-1.17.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata (1.5 kB)
Collecting numpy (from monetdbe)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/e9/b\
5/306ac6ee3f8f0c51abd3664ee8a9b8e264cbf179a860674827151ecc0a9c/numpy-2.2.0-cp311-cp311-macosx_\
14_0_x86_64.whl.metadata
  Downloading numpy-2.2.0-cp311-cp311-macosx_14_0_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 242.6 kB/s eta 0:00:00
Collecting pandas (from monetdbe)
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/a8/\
44/d9502bf0ed197ba9bf1103c9867d5904ddcaf869e52329787fc54ed70cc8/pandas-2.2.3-cp311-cp311-macos\
x_10_9_x86_64.whl.metadata
  Downloading pandas-2.2.3-cp311-cp311-macosx_10_9_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 160.5 kB/s eta 0:00:00
Collecting pycparser (from cffi>=1.0.0->monetdbe)
  Obtaining dependency information for pycparser from https://files.pythonhosted.org/packages/\
13/a3/a812df4e2dd5696d1f351d58b8fe16a405b234ad2886a0dab9183fb78109/pycparser-2.22-py3-none-any\
.whl.metadata
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting python-dateutil>=2.8.2 (from pandas->monetdbe)
  Obtaining dependency information for python-dateutil>=2.8.2 from https://files.pythonhosted.\
org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateuti\
l-2.9.0.post0-py2.py3-none-any.whl.metadata
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->monetdbe)
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packag\
es/11/c3/005fcca25ce078d2cc29fd559379817424e94885510568bc1bc53d7d5846/pytz-2024.2-py2.py3-none\
-any.whl.metadata
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->monetdbe)
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/pack\
ages/a6/ab/7e5f53c3b9d14972843a647d8d7a853969a58aecc7559cb3267302c94774/tzdata-2024.2-py2.py3-\
none-any.whl.metadata
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->monetdbe)
  Obtaining dependency information for six>=1.5 from https://files.pythonhosted.org/packages/b\
7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.\
whl.metadata
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached cffi-1.17.1-cp311-cp311-macosx_10_9_x86_64.whl (182 kB)
Downloading numpy-2.2.0-cp311-cp311-macosx_14_0_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 250.5 kB/s eta 0:00:00
Downloading pandas-2.2.3-cp311-cp311-macosx_10_9_x86_64.whl (12.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 403.4 kB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 235.4 kB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.0/508.0 kB 330.9 kB/s eta 0:00:00
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 245.2 kB/s eta 0:00:00
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: monetdbe
  Building wheel for monetdbe (pyproject.toml) ... done
  Created wheel for monetdbe: filename=monetdbe-0.11-cp311-cp311-macosx_10_9_universal2.whl si\
ze=106615 sha256=79430beeb0d93e1842915b80b0d9b409aa796d2414b12df20d36cc6a1667f3be
  Stored in directory: /Users/jaten/Library/Caches/pip/wheels/e8/c5/f8/ef931e6f38ff30cae644a41\
877d62b45c65f8c6cc351fff354
Successfully built monetdbe
Installing collected packages: pytz, tzdata, six, pycparser, numpy, python-dateutil, cffi, pan\
das, monetdbe
Successfully installed cffi-1.17.1 monetdbe-0.11 numpy-2.2.0 pandas-2.2.3 pycparser-2.22 pytho\
n-dateutil-2.9.0.post0 pytz-2024.2 six-1.17.0 tzdata-2024.2

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
~~~
use:
~~~
$ python
Python 3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import monetdbe
>>> conn = monetdbe.connect(':memory:')
conn = monetdbe.connect(':memory:')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaten/monetdbe/lib/python3.11/site-packages/monetdbe/dbapi2.py", line 42, in connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaten/monetdbe/lib/python3.11/site-packages/monetdbe/connection.py", line 99, in __init__
    self._internal: Optional[Internal] = Internal(
                                         ^^^^^^^^^
  File "/Users/jaten/monetdbe/lib/python3.11/site-packages/monetdbe/_cffi/internal.py", line 137, in __init__
    self._monetdbe_database = self.open()
                              ^^^^^^^^^^^
  File "/Users/jaten/monetdbe/lib/python3.11/site-packages/monetdbe/_cffi/internal.py", line 172, in open
    p_options = ffi.new("monetdbe_options *")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ffi.error: monetdbe_options: wrong offset for field 'remote' (cdef says 16, but C compiler says 24). fix it or use "...;" as the last field in the cdef for monetdbe_options to make it flexible
>>> 
~~~

### Expected behavior

I expected the `conn = monetdbe.connect(':memory:')` line to not return an error.

### MonetDB release

monetdbe-0.11

### Executables source

Release packages

### Operating System

macOS Sonoma 14.0

**Comment by joerivanruth** [comment]
Hi glycerine,

We have a prerelease of the next version of monetdbe, could you try that? To do so, run the following command:
```
pip install --index-url=https://test.pypi.org/simple --extra-index-url=https://pypi.org/simple --pre monetdbe
```

The --index-url and --extra-index-url flags make it install from the test pypi instead of the production pypi. The --pre flag allows it to install prereleases.

If all goes well, you should get version 51.5.0a1. Note that we're switching to a new version number scheme where the first two components (51.5) identify the version of MonetDB this monetdbe is based on, in this case MonetDB 11.51.5 (= Aug2024-SP1).

Joeri

**Comment by glycerine** [comment]
Hi Joeri,

yes, that fixes it. At least, I get no error back now. Thank you!

Jason

~~~
$ rm -rf monetdbe
jaten@Js-MacBook-Pro ~ $ mkdir  monetdbe
jaten@Js-MacBook-Pro ~ $ python3 -m venv monetdbe
jaten@Js-MacBook-Pro ~ $ source monetdbe/bin/activate
(monetdbe) jaten@Js-MacBook-Pro ~ $ pip install --index-url=https://test.pypi.org/simple --extra-index-url=https://pypi.org/simple --pre monetdbe

(monetdbe) jaten@Js-MacBook-Pro ~ $ python
python
Python 3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import monetdbe
import monetdbe
>>> conn = monetdbe.connect(':memory:')
conn = monetdbe.connect(':memory:')
>>> 
~~~
